### ISSUE TITLE
Error? Is it just me? Did I do something wrong?

### ISSUE THREAD

**Issue by EliSussman** [TerrariaPrismTeam/Prism#3]
I tried following the instructions in the README.md file and even made a mod in visual studio (all using the latest build) I build the solution with the projects inside and have the Prism.Terraria.dll file in references as well as a copied over Terraria.exe. 

This brings me to my problem. When I press start or start without debugging, I get an error within the first 5 seconds after pressing the button. This error basically says that the TileCracks.xnb file was not found. I have double checked and inside the Terraria/Conent/Images folder, the file is exactly where the error says it is not.

![untitled](https://cloud.githubusercontent.com/assets/2209109/8855979/0f567306-3136-11e5-8516-2136598cde76.png)

The error is above.

Am I doing something wrong? Is this a bug or something you guys know about? (And especially) Can this be fixed?

EDIT: I'm using Terraria V.1.3.0.6 BTW

**Comment by PoroCYon** [comment]
It's just you, the Content folder must be in the same directory as the Prism.exe **you're running**, not just the directory in your steam folder. (You cloned it in your Terraria steam folder, but that won't make it work automatically.)

**Comment by EliSussman** [comment]
Thank you! I tested what you said by putting a copy of the content folder into the directory with prism.exe, and it Worked! Is this the right way to do this or is their another (more proper) way of doing it? Also 2 questions:

1: How do I load my mod, I don't really get what the README.md says.

2: How do I get rid of an unfatal error saying that the Steamworks.NET.dll that is clearly in the References folder, is missing...

BTW, thank your for this software, I have been waiting for the 1.3 update to start modding Terraria, and tModloader is not updated to include NPCs, (Which is primarily what I want my mod to do).

**Comment by PoroCYon** [comment]
We will expand modding details later, because Prism isn't meant for release just yet (hence the "1.0.0.0 DevBuild"). We're currently trying to make it work on OS X and Linux (1.3.0.7 is just released), then we'll be adding more hooks & moddable entity types, etc.

Copy the bin\Debug folder of the example mod to Documents\My Games\Terraria\Prism\Mods (and rename it to Prism.ExampleMod for convenience). All Prism mods will have such structure (for now).

I need more information on the Steamworks.NET.dll is missing error (i.e. which project, when, etc).

**Comment by EliSussman** [comment]
I did what you said, and what a surprise :-P It loaded my mod.

I do know this is a development build, but I am just trying to get as much done with my mod now, so I have less work when the actual releases come out. :-)

Last Question: Is there a way to add recipes or ways to spawn NPCs/Get Items in game, right now? I'm guessing that there is not by looking at the code, but you may know something I don't. If there isn't, do I wait for a release that adds them, or is there a way around it? I just would like to test my NPCs and/or my Items. :-)

**Comment by PoroCYon** [comment]
Recipes can be hacked in using the Recipe class directly in ModDef.OnAllModsLoaded, but there's no way to spawn NPCs currently.

**Comment by EliSussman** [comment]
@PoroCYon Do you need help with anything intermediate or simple, maybe something that just takes time or you don't want to do by yourself? I am willing to help you.

**Comment by PoroCYon** [comment]
We're currently working on supporting Prism on Linux and OS X (it currently builds, but we're getting some runtime errors), wh and MiraiMai are helping me.

After that, lots of entity hooks will need to be added, projectile support, tile & wall support, a nice way of creating recipes, World, WorldGen & Player hooks, etc. All help is welcome, because there is still a lot to do.

You can always join the #tapi IRC channel on EsperNet (irc.esper.net, port 6667). (I live in Belgium, so you can expect when I'll be online or not. I use a bouncer, so I will be in the userlist).
